---
title: "Week 8 Discussion Questions"
author: "Trevor Hewitt & M Zimbric"
date: "October 29, 2015"
output: pdf_document
---

##Trussell, G. C., Ewanchuk, P. J., & Bertness, M. D. 2002. Field evidence of trait-mediated indirect interactions in a rocky intertidal food web. *Ecology Letters* 5(2), 241–245

##Schmitz, O. J., Krivan, V., & Ovadia, O. 2004. Trophic cascades: The primacy of trait-mediated indirect interactions. *Ecology Letters* 7(2), 153–163. 

__Summary:__

Trussell et al. performed a test of the strength of TMII in an intertidal ecosystem. The study system includes the predatory green crab (*Carcinus maenas*), its prey an herbivorous snail (*Littorina littorea*), and the fucoid algae the snail feeds on. Algae were allowed to grow on tile plots protected from snail grazing and then snails were introduced to feed on half the plots. Half of the plots were surrounded by caged green crabs. Plots with crabs and snails present exhibited similar fucoid densitiies as plots where snails were absent and the density of snails was significantly higher in plots without crabs. These results suggest that reduced grazing caused by predator cues contributes strongly to the positive correlation between crab and algae densities observed in previous studies. 

Trophic cascades are an important concept in ecology; however, many important assumptions associated with this concept have been shown to be an oversimplification. All predators and all prey species in a system do not function the same, and the interactions between predators and prey can change species behaviors. Changes in behavior can cause complex food web interactions. These are called trait-mediated indirect interactions (TMII). Schmitz et al. review a number of different studies and develop a framework for predicting the relative importance of TMIIs and the classic density-mediated indirect interactions (DMII) based on the habitat preferences of predator and prey as well as general predator behavior. The authors argue that more research should be done to understand TMIIs and to develop a framework for predicting when TMIIs will likely be an important effect in a system.

__Pre-Discussion Questions:__

* The relative strengths of density-mediated indirect interactions (DMII) and trait-mediated indirect interactions (TMII) on trophic cascade are often difficult to determine. Do you see this as problematic? How might researchers address this?

* Do you think, in general, trophic cascades are more likely to be impacted by TMIIs or DMIIs?

* Do you think figure 3 is a general enough framework to be applied to most ecological systems? Why or why not?

* List two limitations of the experimental design in Trussell et al.?  

* Do the results showing lower snail density in crab plots contradict the authors' conclusions about trait mediation? Why or why not? 